In [1]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler,StandardScaler,Normalizer

### 无量纲化处理

消除因为样本特征之间量级不同而导致的算法不精确问题

- 1.有些具有伸缩不变性的算法，可以不做无量纲处理
- 2.但是无量纲处理一般来说，不论任何算法都可以做，有利而无害

In [2]:
data = load_iris().data
target = load_iris().target

In [3]:
# 区缩放法
MinMaxScaler().fit_transform(data)

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [4]:
# 标准化
StandardScaler().fit_transform(data)

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [5]:
# 归一化
Normalizer().fit_transform(data)

array([[0.80377277, 0.55160877, 0.22064351, 0.0315205 ],
       [0.82813287, 0.50702013, 0.23660939, 0.03380134],
       [0.80533308, 0.54831188, 0.2227517 , 0.03426949],
       [0.80003025, 0.53915082, 0.26087943, 0.03478392],
       [0.790965  , 0.5694948 , 0.2214702 , 0.0316386 ],
       [0.78417499, 0.5663486 , 0.2468699 , 0.05808704],
       [0.78010936, 0.57660257, 0.23742459, 0.0508767 ],
       [0.80218492, 0.54548574, 0.24065548, 0.0320874 ],
       [0.80642366, 0.5315065 , 0.25658935, 0.03665562],
       [0.81803119, 0.51752994, 0.25041771, 0.01669451],
       [0.80373519, 0.55070744, 0.22325977, 0.02976797],
       [0.786991  , 0.55745196, 0.26233033, 0.03279129],
       [0.82307218, 0.51442011, 0.24006272, 0.01714734],
       [0.8025126 , 0.55989251, 0.20529392, 0.01866308],
       [0.81120865, 0.55945424, 0.16783627, 0.02797271],
       [0.77381111, 0.59732787, 0.2036345 , 0.05430253],
       [0.79428944, 0.57365349, 0.19121783, 0.05883625],
       [0.80327412, 0.55126656,

In [11]:
### 二值化处理
from sklearn.preprocessing import Binarizer
import numpy as np

train = np.array([[10,11,15,9,6,7,9,8]])

Binarizer(threshold=10).fit_transform(train)

array([[0, 1, 1, 0, 0, 0, 0, 0]])

In [16]:
from numpy import vstack, array, nan
from sklearn.preprocessing import Imputer

#缺失值计算，返回值为计算缺失值后的数据
#参数missing_value为缺失值的表示形式，默认为NaN
#参数strategy为缺失值填充方式，默认为mean（均值）
train = vstack((array([nan, nan, nan, nan]), data))
# display(train)
# 有三种值可以填充strategy
# 平均值 mean
# 中值 median
# 众数 most_frequent
Imputer(strategy='mean').fit_transform(train)

array([[5.84333333, 3.054     , 3.75866667, 1.19866667],
       [5.1       , 3.5       , 1.4       , 0.2       ],
       [4.9       , 3.        , 1.4       , 0.2       ],
       [4.7       , 3.2       , 1.3       , 0.2       ],
       [4.6       , 3.1       , 1.5       , 0.2       ],
       [5.        , 3.6       , 1.4       , 0.2       ],
       [5.4       , 3.9       , 1.7       , 0.4       ],
       [4.6       , 3.4       , 1.4       , 0.3       ],
       [5.        , 3.4       , 1.5       , 0.2       ],
       [4.4       , 2.9       , 1.4       , 0.2       ],
       [4.9       , 3.1       , 1.5       , 0.1       ],
       [5.4       , 3.7       , 1.5       , 0.2       ],
       [4.8       , 3.4       , 1.6       , 0.2       ],
       [4.8       , 3.        , 1.4       , 0.1       ],
       [4.3       , 3.        , 1.1       , 0.1       ],
       [5.8       , 4.        , 1.2       , 0.2       ],
       [5.7       , 4.4       , 1.5       , 0.4       ],
       [5.4       , 3.9       ,

In [18]:
import pandas as pd
from pandas import Series,DataFrame

DataFrame(train).fillna('1')

0    1    2    3
0      1    1    1    1
1    5.1  3.5  1.4  0.2
2    4.9    3  1.4  0.2
3    4.7  3.2  1.3  0.2
4    4.6  3.1  1.5  0.2
5      5  3.6  1.4  0.2
6    5.4  3.9  1.7  0.4
7    4.6  3.4  1.4  0.3
8      5  3.4  1.5  0.2
9    4.4  2.9  1.4  0.2
10   4.9  3.1  1.5  0.1
11   5.4  3.7  1.5  0.2
12   4.8  3.4  1.6  0.2
13   4.8    3  1.4  0.1
14   4.3    3  1.1  0.1
15   5.8    4  1.2  0.2
16   5.7  4.4  1.5  0.4
17   5.4  3.9  1.3  0.4
18   5.1  3.5  1.4  0.3
19   5.7  3.8  1.7  0.3
20   5.1  3.8  1.5  0.3
21   5.4  3.4  1.7  0.2
22   5.1  3.7  1.5  0.4
23   4.6  3.6    1  0.2
24   5.1  3.3  1.7  0.5
25   4.8  3.4  1.9  0.2
26     5    3  1.6  0.2
27     5  3.4  1.6  0.4
28   5.2  3.5  1.5  0.2
29   5.2  3.4  1.4  0.2
..   ...  ...  ...  ...
121  6.9  3.2  5.7  2.3
122  5.6  2.8  4.9    2
123  7.7  2.8  6.7    2
124  6.3  2.7  4.9  1.8
125  6.7  3.3  5.7  2.1
126  7.2  3.2    6  1.8
127  6.2  2.8  4.8  1.8
128  6.1    3  4.9  1.8
129  6.4  2.8  5.6  2.1
130  7.2    3  5.8  1.6
131  7.4  2.8  6.1  1.9
132  7.9  3.8  6.4    2
133  6.4  2.8  5.6  2.2
134  6.3  2.8  5.1  1.5
135  6.1  2.6  5.6  1.4
136  7.7    3  6.1  2.3
137  6.3  3.4  5.6  2.4
138  6.4  3.1  5.5  1.8
139    6    3  4.8  1.8
140  6.9  3.1  5.4  2.1
141  6.7  3.1  5.6  2.4
142  6.9  3.1  5.1  2.3
143  5.8  2.7  5.1  1.9
144  6.8  3.2  5.9  2.3
145  6.7  3.3  5.7  2.5
146  6.7    3  5.2  2.3
147  6.3  2.5    5  1.9
148  6.5    3  5.2    2
149  6.2  3.4  5.4  2.3
150  5.9    3  5.1  1.8

[151 rows x 4 columns]

In [28]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
# 哑编码
train = np.array([['male','yes'],
                  ['femal','no'],
                  ['male','yes'],
                  ['femal','yes'],
                  ['femal','yes'],
                  ['femal','no'],
                  ['male','no'],
                  ['male','yes'],
                  ['femal','no'],
                  ['male','no'],])
# 先使用labelencoder转换成数字
lable_enc1 = LabelEncoder()
enc1 = lable_enc1.fit_transform(train[:,0])
# 独热编码，把数字转换成矩阵，消除特征间的关联性
onehot_enc1 = OneHotEncoder()
# 训练的数据必须是列向量，跟机器学习模型是一致的
matrix1 = onehot_enc1.fit_transform(enc1.reshape(-1,1))
# 提取矩阵结果todense()
matrix1.todense()

lable_enc2 = LabelEncoder()
enc2 = lable_enc2.fit_transform(train[:,1])
onehot_enc2 = OneHotEncoder()
matrix2 = onehot_enc2.fit_transform(enc2.reshape(-1,1))
matrix2.todense()

n_train = np.concatenate((matrix1.todense(),matrix2.todense()),axis=1)
n_train

matrix([[0., 1., 0., 1.],
        [1., 0., 1., 0.],
        [0., 1., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 1., 0.],
        [0., 1., 1., 0.],
        [0., 1., 0., 1.],
        [1., 0., 1., 0.],
        [0., 1., 1., 0.]])